/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ledTOnum_15 (
    input [36:0] led,
    output reg [15:0] userAnswer
  );
  
  
  
  localparam P0 = 37'h0000000001;
  
  localparam P1 = 37'h0000000002;
  
  localparam P2 = 37'h0000000004;
  
  localparam P3 = 37'h0000000008;
  
  localparam P4 = 37'h0000000010;
  
  localparam P5 = 37'h0000000020;
  
  localparam P6 = 37'h0000000040;
  
  localparam P7 = 37'h0000000080;
  
  localparam P8 = 37'h0000000100;
  
  localparam P9 = 37'h0000000200;
  
  localparam P10 = 37'h0000000400;
  
  localparam P11 = 37'h0000000800;
  
  localparam P12 = 37'h0000001000;
  
  localparam P13 = 37'h0000002000;
  
  localparam P14 = 37'h0000004000;
  
  localparam P15 = 37'h0000008000;
  
  localparam P16 = 37'h0000010000;
  
  localparam P17 = 37'h0000020000;
  
  localparam P18 = 37'h0000040000;
  
  localparam N18 = 37'h0000080000;
  
  localparam N17 = 37'h0000100000;
  
  localparam N16 = 37'h0000200000;
  
  localparam N15 = 37'h0000400000;
  
  localparam N14 = 37'h0000800000;
  
  localparam N13 = 37'h0001000000;
  
  localparam N12 = 37'h0002000000;
  
  localparam N11 = 37'h0004000000;
  
  localparam N10 = 37'h0008000000;
  
  localparam N9 = 37'h0010000000;
  
  localparam N8 = 37'h0020000000;
  
  localparam N7 = 37'h0040000000;
  
  localparam N6 = 37'h0080000000;
  
  localparam N5 = 37'h0100000000;
  
  localparam N4 = 37'h0200000000;
  
  localparam N3 = 37'h0400000000;
  
  localparam N2 = 37'h0800000000;
  
  localparam N1 = 37'h1000000000;
  
  always @* begin
    userAnswer = 1'h0;
    
    case (led[0+36-:37])
      37'h0000000001: begin
        userAnswer = 16'h0000;
      end
      37'h0000000002: begin
        userAnswer = 16'h0001;
      end
      37'h0000000004: begin
        userAnswer = 16'h0002;
      end
      37'h0000000008: begin
        userAnswer = 16'h0003;
      end
      37'h0000000010: begin
        userAnswer = 16'h0004;
      end
      37'h0000000020: begin
        userAnswer = 16'h0005;
      end
      37'h0000000040: begin
        userAnswer = 16'h0006;
      end
      37'h0000000080: begin
        userAnswer = 16'h0007;
      end
      37'h0000000100: begin
        userAnswer = 16'h0008;
      end
      37'h0000000200: begin
        userAnswer = 16'h0009;
      end
      37'h0000000400: begin
        userAnswer = 16'h000a;
      end
      37'h0000000800: begin
        userAnswer = 16'h000b;
      end
      37'h0000001000: begin
        userAnswer = 16'h000c;
      end
      37'h0000002000: begin
        userAnswer = 16'h000d;
      end
      37'h0000004000: begin
        userAnswer = 16'h000e;
      end
      37'h0000008000: begin
        userAnswer = 16'h000f;
      end
      37'h0000010000: begin
        userAnswer = 16'h0010;
      end
      37'h0000020000: begin
        userAnswer = 16'h0011;
      end
      37'h0000040000: begin
        userAnswer = 16'h0012;
      end
      37'h1000000000: begin
        userAnswer = 16'hffff;
      end
      37'h0800000000: begin
        userAnswer = 16'hfffe;
      end
      37'h0400000000: begin
        userAnswer = 16'hfffd;
      end
      37'h0200000000: begin
        userAnswer = 16'hfffc;
      end
      37'h0100000000: begin
        userAnswer = 16'hfffb;
      end
      37'h0080000000: begin
        userAnswer = 16'hfffa;
      end
      37'h0040000000: begin
        userAnswer = 16'hfff9;
      end
      37'h0020000000: begin
        userAnswer = 16'hfff8;
      end
      37'h0010000000: begin
        userAnswer = 16'hfff7;
      end
      37'h0008000000: begin
        userAnswer = 16'hfff6;
      end
      37'h0004000000: begin
        userAnswer = 16'hfff5;
      end
      37'h0002000000: begin
        userAnswer = 16'hfff4;
      end
      37'h0001000000: begin
        userAnswer = 16'hfff3;
      end
      37'h0000800000: begin
        userAnswer = 16'hfff2;
      end
      37'h0000400000: begin
        userAnswer = 16'hfff1;
      end
      37'h0000200000: begin
        userAnswer = 16'hfff0;
      end
      37'h0000100000: begin
        userAnswer = 16'hffef;
      end
      37'h0000080000: begin
        userAnswer = 16'hffee;
      end
      default: begin
        userAnswer = 1'h0;
      end
    endcase
  end
endmodule
