/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module opTOalufn_24 (
    input [1:0] opled,
    output reg [5:0] ledalufn
  );
  
  
  
  always @* begin
    ledalufn = 1'h0;
    
    case (opled)
      1'h1: begin
        ledalufn = 1'h0;
      end
      2'h2: begin
        ledalufn = 1'h1;
      end
      default: begin
        ledalufn = 1'h0;
      end
    endcase
  end
endmodule
