/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rand_digit_19 (
    input [15:0] in,
    output reg [6:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (in)
      1'h0: begin
        out = 14'h1fbf;
      end
      1'h1: begin
        out = 14'h1f86;
      end
      2'h2: begin
        out = 14'h1fdb;
      end
      2'h3: begin
        out = 14'h1fcf;
      end
      3'h4: begin
        out = 14'h1fe6;
      end
      3'h5: begin
        out = 14'h1fed;
      end
      3'h6: begin
        out = 14'h1ffd;
      end
      3'h7: begin
        out = 14'h1f87;
      end
      4'h8: begin
        out = 14'h1fff;
      end
      4'h9: begin
        out = 14'h1fef;
      end
      $signed(2'h3): begin
        out = 14'h2006;
      end
      $signed(3'h6): begin
        out = 14'h205b;
      end
      $signed(3'h5): begin
        out = 14'h204f;
      end
      $signed(4'hc): begin
        out = 14'h2066;
      end
      $signed(4'hb): begin
        out = 14'h206d;
      end
      $signed(4'ha): begin
        out = 14'h207d;
      end
      $signed(4'h9): begin
        out = 14'h2007;
      end
      $signed(5'h18): begin
        out = 14'h207f;
      end
      $signed(5'h17): begin
        out = 14'h206f;
      end
      default: begin
        out = 14'h0000;
      end
    endcase
  end
endmodule
