/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sevenseg_level_7 (
    input [15:0] level,
    output reg [6:0] out
  );
  
  
  
  wire [7-1:0] M_leveldig_out;
  reg [16-1:0] M_leveldig_in;
  level_digit_18 leveldig (
    .in(M_leveldig_in),
    .out(M_leveldig_out)
  );
  
  always @* begin
    M_leveldig_in = level;
    out = M_leveldig_out;
  end
endmodule
