/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wheelLED_2 (
    input clk,
    input rst,
    input select_button,
    input reset_button,
    output reg [36:0] led
  );
  
  
  
  localparam BEGIN_ledstate = 6'd0;
  localparam L0_ledstate = 6'd1;
  localparam L1_ledstate = 6'd2;
  localparam L2_ledstate = 6'd3;
  localparam L3_ledstate = 6'd4;
  localparam L4_ledstate = 6'd5;
  localparam L5_ledstate = 6'd6;
  localparam L6_ledstate = 6'd7;
  localparam L7_ledstate = 6'd8;
  localparam L8_ledstate = 6'd9;
  localparam L9_ledstate = 6'd10;
  localparam L10_ledstate = 6'd11;
  localparam L11_ledstate = 6'd12;
  localparam L12_ledstate = 6'd13;
  localparam L13_ledstate = 6'd14;
  localparam L14_ledstate = 6'd15;
  localparam L15_ledstate = 6'd16;
  localparam L16_ledstate = 6'd17;
  localparam L17_ledstate = 6'd18;
  localparam L18_ledstate = 6'd19;
  localparam LN18_ledstate = 6'd20;
  localparam LN17_ledstate = 6'd21;
  localparam LN16_ledstate = 6'd22;
  localparam LN15_ledstate = 6'd23;
  localparam LN14_ledstate = 6'd24;
  localparam LN13_ledstate = 6'd25;
  localparam LN12_ledstate = 6'd26;
  localparam LN11_ledstate = 6'd27;
  localparam LN10_ledstate = 6'd28;
  localparam LN9_ledstate = 6'd29;
  localparam LN8_ledstate = 6'd30;
  localparam LN7_ledstate = 6'd31;
  localparam LN6_ledstate = 6'd32;
  localparam LN5_ledstate = 6'd33;
  localparam LN4_ledstate = 6'd34;
  localparam LN3_ledstate = 6'd35;
  localparam LN2_ledstate = 6'd36;
  localparam LN1_ledstate = 6'd37;
  localparam WIN_ledstate = 6'd38;
  
  reg [5:0] M_ledstate_d, M_ledstate_q = BEGIN_ledstate;
  wire [37-1:0] M_shift_out;
  reg [37-1:0] M_shift_led;
  reg [37-1:0] M_shift_shifter;
  shiftled_16 shift (
    .clk(clk),
    .rst(rst),
    .led(M_shift_led),
    .shifter(M_shift_shifter),
    .out(M_shift_out)
  );
  
  localparam P0 = 37'h0000000001;
  
  localparam P1 = 37'h0000000002;
  
  localparam P2 = 37'h0000000004;
  
  localparam P3 = 37'h0000000008;
  
  localparam P4 = 37'h0000000010;
  
  localparam P5 = 37'h0000000020;
  
  localparam P6 = 37'h0000000040;
  
  localparam P7 = 37'h0000000080;
  
  localparam P8 = 37'h0000000100;
  
  localparam P9 = 37'h0000000200;
  
  localparam P10 = 37'h0000000400;
  
  localparam P11 = 37'h0000000800;
  
  localparam P12 = 37'h0000001000;
  
  localparam P13 = 37'h0000002000;
  
  localparam P14 = 37'h0000004000;
  
  localparam P15 = 37'h0000008000;
  
  localparam P16 = 37'h0000010000;
  
  localparam P17 = 37'h0000020000;
  
  localparam P18 = 37'h0000040000;
  
  localparam N18 = 37'h0000080000;
  
  localparam N17 = 37'h0000100000;
  
  localparam N16 = 37'h0000200000;
  
  localparam N15 = 37'h0000400000;
  
  localparam N14 = 37'h0000800000;
  
  localparam N13 = 37'h0001000000;
  
  localparam N12 = 37'h0002000000;
  
  localparam N11 = 37'h0004000000;
  
  localparam N10 = 37'h0008000000;
  
  localparam N9 = 37'h0010000000;
  
  localparam N8 = 37'h0020000000;
  
  localparam N7 = 37'h0040000000;
  
  localparam N6 = 37'h0080000000;
  
  localparam N5 = 37'h0100000000;
  
  localparam N4 = 37'h0200000000;
  
  localparam N3 = 37'h0400000000;
  
  localparam N2 = 37'h0800000000;
  
  localparam N1 = 37'h1000000000;
  
  always @* begin
    M_ledstate_d = M_ledstate_q;
    
    led = 37'h0000000000;
    M_shift_led = 1'h0;
    M_shift_shifter = 1'h0;
    
    case (M_ledstate_q)
      BEGIN_ledstate: begin
        if (select_button == 1'h1) begin
          M_ledstate_d = L0_ledstate;
        end
      end
      L0_ledstate: begin
        M_shift_led = 37'h0000000001;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L1_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000001;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L1_ledstate: begin
        M_shift_led = 37'h0000000002;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L2_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000002;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L2_ledstate: begin
        M_shift_led = 37'h0000000004;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L3_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000004;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L3_ledstate: begin
        M_shift_led = 37'h0000000008;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L3_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000008;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L4_ledstate: begin
        M_shift_led = 37'h0000000010;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L5_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000010;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L5_ledstate: begin
        M_shift_led = 37'h0000000020;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L6_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000020;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L6_ledstate: begin
        M_shift_led = 37'h0000000040;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L7_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000040;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L7_ledstate: begin
        M_shift_led = 37'h0000000080;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L8_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000080;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L8_ledstate: begin
        M_shift_led = 37'h0000000100;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L9_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000100;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L9_ledstate: begin
        M_shift_led = 37'h0000000200;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L10_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000200;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L10_ledstate: begin
        M_shift_led = 37'h0000000400;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L11_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000400;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L11_ledstate: begin
        M_shift_led = 37'h0000000800;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L12_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000000800;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L12_ledstate: begin
        M_shift_led = 37'h0000001000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L13_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000001000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L13_ledstate: begin
        M_shift_led = 37'h0000002000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L14_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000002000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L14_ledstate: begin
        M_shift_led = 37'h0000004000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L15_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000004000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L15_ledstate: begin
        M_shift_led = 37'h0000008000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L16_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000008000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L16_ledstate: begin
        M_shift_led = 37'h0000010000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L17_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000010000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L17_ledstate: begin
        M_shift_led = 37'h0000020000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L18_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000020000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      L18_ledstate: begin
        M_shift_led = 37'h0000040000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN18_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000040000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN18_ledstate: begin
        M_shift_led = 37'h0000080000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN17_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000080000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN17_ledstate: begin
        M_shift_led = 37'h0000100000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN16_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000100000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN16_ledstate: begin
        M_shift_led = 37'h0000200000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN15_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000200000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN15_ledstate: begin
        M_shift_led = 37'h0000400000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN14_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000400000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN14_ledstate: begin
        M_shift_led = 37'h0000800000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN13_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0000800000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN13_ledstate: begin
        M_shift_led = 37'h0001000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN12_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0001000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN12_ledstate: begin
        M_shift_led = 37'h0002000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN11_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0002000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN11_ledstate: begin
        M_shift_led = 37'h0004000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN10_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0004000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN10_ledstate: begin
        M_shift_led = 37'h0008000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN9_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0008000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN9_ledstate: begin
        M_shift_led = 37'h0010000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN8_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0010000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN8_ledstate: begin
        M_shift_led = 37'h0020000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN7_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0020000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN7_ledstate: begin
        M_shift_led = 37'h0040000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN6_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0040000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN6_ledstate: begin
        M_shift_led = 37'h0080000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN5_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0080000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN5_ledstate: begin
        M_shift_led = 37'h0100000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN4_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0100000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN4_ledstate: begin
        M_shift_led = 37'h0200000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN3_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0200000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN3_ledstate: begin
        M_shift_led = 37'h0400000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN2_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0400000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN2_ledstate: begin
        M_shift_led = 37'h0800000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = LN1_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h0800000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
      LN1_ledstate: begin
        M_shift_led = 37'h1000000000;
        M_shift_shifter = 37'h0000000001;
        if (select_button == 1'h0 && reset_button == 1'h0) begin
          led = M_shift_out;
          M_ledstate_d = L0_ledstate;
        end else begin
          if (select_button == 1'h1 && reset_button == 1'h0) begin
            led = 37'h1000000000;
          end else begin
            led = 37'h0000000000;
          end
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ledstate_q <= 1'h0;
    end else begin
      M_ledstate_q <= M_ledstate_d;
    end
  end
  
endmodule
